/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;


import java.awt.event.ActionListener;


/**
 *
 * @author monge
 */
public class PanelMenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelMenuPrincipal
     */
  
    
    public PanelMenuPrincipal() {
        initComponents();      
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        pickPlayer = new javax.swing.JButton();
        topScorers = new javax.swing.JButton();
        options = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        sidewalk = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        sky = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/misc/titles/start.gif"))); // NOI18N
        start.setActionCommand("start");
        start.setBorderPainted(false);
        start.setContentAreaFilled(false);
        add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 150, 60));

        pickPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/misc/titles/pick-player.gif"))); // NOI18N
        pickPlayer.setActionCommand("pickPlayer");
        pickPlayer.setContentAreaFilled(false);
        pickPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickPlayerActionPerformed(evt);
            }
        });
        add(pickPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 320, -1));

        topScorers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/misc/titles/top-scorers.gif"))); // NOI18N
        topScorers.setActionCommand("topScorers");
        topScorers.setBorderPainted(false);
        topScorers.setContentAreaFilled(false);
        add(topScorers, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        options.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/misc/titles/options.gif"))); // NOI18N
        options.setActionCommand("options");
        options.setBorderPainted(false);
        options.setContentAreaFilled(false);
        add(options, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/misc/titles/quit.gif"))); // NOI18N
        quit.setActionCommand("quit");
        quit.setBorderPainted(false);
        quit.setContentAreaFilled(false);
        add(quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.gif"))); // NOI18N
        add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        sidewalk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondos/sidewalk.png"))); // NOI18N
        add(sidewalk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        city.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondos/city.png"))); // NOI18N
        add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        sky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/fondos/sky.png"))); // NOI18N
        add(sky, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 449));
    }// </editor-fold>//GEN-END:initComponents

    private void pickPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pickPlayerActionPerformed

    public void escuchar(ActionListener controller) {
           start.addActionListener(controller);
           options.addActionListener(controller);
           topScorers.addActionListener(controller);
           quit.addActionListener(controller);
           pickPlayer.addActionListener(controller);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city;
    private javax.swing.JLabel logo;
    private javax.swing.JButton options;
    private javax.swing.JButton pickPlayer;
    private javax.swing.JButton quit;
    private javax.swing.JLabel sidewalk;
    private javax.swing.JLabel sky;
    private javax.swing.JButton start;
    private javax.swing.JButton topScorers;
    // End of variables declaration//GEN-END:variables

}
